---
title: "ENV 790.30 - Time Series Analysis for Energy Data | Spring 2023"
subtitle: "Assignment 1 - Due date 01/24/23"
<<<<<<< HEAD:Assignments/KarenThornton_TSA_A01_Sp23.Rmd
author: "Karen Thornton"
=======
<<<<<<< HEAD
author: "Luana"
>>>>>>> 7ab51001fb26c7f98e21f745884a2fb9b769989d:Assignments/TSA_A01_Sp22.Rmd
output: pdf_document
geometry: margin=2.54cm
=======
>>>>>>> 005f4d07228dca10372d5c5bd131f85203a87c16
---

## Directions

Before making any edits to this file, please rename it such that it includes your first and last name (e.g., "LuanaLima_TSA_A01_Sp23.Rmd")

Once you have this renamed file open in RStudio, the first thing you will do is replace "Student Name" on line 3 with your name. 
Then you will start working through the assignment by  **creating code and output** that answer each question. Be sure to use this assignment document. Your report should contain the answer to each question and any plots/tables you obtained (when applicable).

When you have completed the assignment, **Knit** the text and code into a single PDF file.  Submit this pdf using Sakai. 

## Questions

Q1. What are your previous experiences with time series analysis, R, and Git? 

<<<<<<< HEAD:Assignments/KarenThornton_TSA_A01_Sp23.Rmd

> Answer: I don't have much experience with time series apart from the short section in EDA last year. I have experience with R from EDA and a little from my internship this past summer. My experience with Git is from EDA as well. 
=======
<<<<<<< HEAD
> Answer: None
>>>>>>> 7ab51001fb26c7f98e21f745884a2fb9b769989d:Assignments/TSA_A01_Sp22.Rmd
=======
>>>>>>> 005f4d07228dca10372d5c5bd131f85203a87c16


Q2. (Only if you choose to use git) Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file as instructed on the recorded video "Getting started with Git and Github". 

> Answer: https://github.com/karenthornton/TimeSeriesAnalysis_Sp23.git


Q3. For this part we just want to see the path to your R project. No need to do anything. The output will be automatically generated once you knit you file. 

> Answer: This is my working directory:

```{r}
getwd()
````


